name: generate breakout svg

on:
  schedule:
    - cron: "23 18 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: khaingmyozaw

      - name: Debug SVG Output 
        run: |
          ls -lh output
          head -n 20 output/light.svg
          head -n 20 output/dark.svg

      - name: Move generated SVGs
        run: |
          mkdir -p images
          cp output/light.svg images/breakout-light.svg
          cp output/dark.svg images/breakout-dark.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs
        run: |
          git add images/breakout-light.svg images/breakout-dark.svg
          git commit -m "chore: update breakout SVGs" || echo "No changes to commit"
          git pull --rebase origin main
          git push